version: 2.1
description: Test CCI conditionals

commands:
  do_release:
    steps:
      - run:
          name: Do actual release thing 1
          working_directory: ./cliv2
          command: |
            echo "Do actual release thing 1"
      - run:
          name: Do actual release thing 2
          working_directory: ./cliv2
          command: |
            echo "Do actual release thing 2"

jobs:
  test:
    machine:
      image: ubuntu-2204:2022.07.1
    working_directory: /home/circleci/test_cci_conditionals
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Do testing stuff
          command: echo "Doing testing"

  deploy:
    machine:
      image: ubuntu-2204:2022.07.1
    working_directory: /home/circleci/test_cci_conditionals
    steps:
      - checkout
      - attach_workspace:
          at: .
      
      # the "real work of the release is done here
      # Then when condition can look at a pipeline parameter
      # equal: [ "my-scheduled-release", << pipeline.schedule.name >> ]   # `my-scheduled-release` is the name I gave to the scheduled pipeline trigger
      - when:
          condition:
            equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]  # these are built-in names
          steps:
            - do_release

workflows:
  build:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main
